# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-06-01 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_sentence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentence',
            old_name='article',
            new_name='document',
        ),
    ]
