# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-06-09 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20190601_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='plag',
            field=models.BooleanField(default=False),
        ),
    ]
